apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ip-app-doc-converter-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ip-app-doc-converter
  minReplicas: 1
  maxReplicas: 5