apiVersion: v1
kind: PersistentVolume
metadata:
  name: ip-app-gateway-nginx-static-pv-95
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.3.6.144
    path: "/ip_data_95/static"
