apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-attachment
  labels:
    app: ip-app-attachment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-app-attachment
  template:
    metadata:
      labels:
        app: ip-app-attachment
    spec:
      containers:
        - name: ip-app-attachment
          image: ip-k8s-lcm01:5000/ip-app-attachment:9_5
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              port: 8082
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 30
          volumeMounts:
          - name: ip-app-attachment-data
            mountPath: /ipdata/attachments
          env:
            - name: IP_APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_HOST
                  name: ip-app-db-configmap
            - name: IP_APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_PORT
                  name: ip-app-db-configmap
            - name: IP_APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_NAME
                  name: ip-app-db-configmap
            - name: IP_APP_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_USERNAME
                  name: ip-app-db-configmap
            - name: IP_APP_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_PASSWORD
                  name: ip-app-db-configmap
      volumes:
      - name: ip-app-attachment-data
        persistentVolumeClaim:
          claimName: ip-app-attachment-data-pvc
