apiVersion: v1
kind: Service
metadata:
  name: ip-app-gateway-nginx
spec:
  ports:
  - port: 80
    name: plaintext
    targetPort: 80
    nodePort: 30009
  selector:
    app: ip-app-gateway-nginx
  type: NodePort
