apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
spec:
  selector:
    app: elasticsearch-logging
  ports:
    - port: 9201
      targetPort: 9200
      name: plaintext
