apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-logic
  labels:
    app: ip-app-logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-app-logic
  template:
    metadata:
      labels:
        app: ip-app-logic
    spec:
      containers:
      - name: ip-app
        image: ip-k8s-lcm01:5000/ip-app-logic-customjars2:9_5
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /json/cluster/local/actuator/health/liveness
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 120
        readinessProbe:
          httpGet:
            path: /json/cluster/local/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - name: ip-app-logic-templates
          mountPath: /ipdata/templates
        env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: IP_APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_HOST
                  name: ip-app-db-configmap
            - name: IP_APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_PORT
                  name: ip-app-db-configmap
            - name: IP_APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_NAME
                  name: ip-app-db-configmap
            - name: IP_APP_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_USERNAME
                  name: ip-app-db-configmap
            - name: IP_APP_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_PASSWORD
                  name: ip-app-db-configmap
            - name: IP_APP_DB_QUERY_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_QUERY_TIMEOUT
                  name: ip-app-db-configmap
            - name: IP_APP_IS_LOCALIZATION_ON
              value: "true"
            - name: IP_APP_LOGIN_COMPLEXITY_REGEX
              value: "^[\\S]{4,12}$"
            - name: IP_APP_LOGIN_COMPLEXITY_MESSAGE
              value: "Логин должен иметь длину не менее 4 и не более 12 символов"
            - name: IP_APP_PASSWORD_COMPLEXITY_REGEX
              value: "^(?:(?=.*[a-z])(?:(?=.*[A-Z])(?=.*[\\d\\W])|(?=.*\\W)(?=.*\\d))|(?=.*\\W)(?=.*[A-Z])(?=.*\\d)).{12,}$"
            - name: IP_APP_PASSWORD_COMPLEXITY_MESSAGE
              value: "\u0414\u043B\u0438\u043D\u0430 \u043F\u0430\u0440\u043E\u043B\u044F \u0434\u043E\u0436\u043D\u0430 \u0431\u044B\u0442\u044C \u043D\u0435 \u043C\u0435\u043D\u0435\u0435 12 \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432 \u0438 \u043F\u0430\u0440\u043E\u043B\u044C \u0434\u043E\u043B\u0436\u0435\u043D \u0441\u043E\u0434\u0435\u0440\u0436\u0430\u0442\u044C \u0441\u0438\u043C\u0432\u043E\u043B\u044B \u043A\u0430\u043A \u043C\u0438\u043D\u0438\u043C\u0443\u043C 3-\u0445 \u0432\u0438\u0434\u043E\u0432 \u0438\u0437  \u0441\u043B\u0435\u0434\u0443\u044E\u0449\u0438\u0445 \u043F\u043E\u0434\u043C\u043D\u043E\u0436\u0435\u0441\u0442\u0432: \n - A-Z (\u0431\u0443\u043A\u0432\u044B \u0432 \u0432\u0435\u0440\u0445\u043D\u0435\u043C \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0435);\n - a-z   (\u0431\u0443\u043A\u0432\u044B \u0432 \u043D\u0438\u0436\u043D\u0435\u043C \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0435);\n - 0-9  (\u0446\u0438\u0444\u0440\u044B);\n - ~+$&#@%  \u0438 \u0442.\u043F. (\u0441\u043F\u0435\u0446\u0441\u0438\u043C\u0432\u043E\u043B\u044B);"
      volumes:
      - name: ip-app-logic-templates
        persistentVolumeClaim:
          claimName: ip-app-logic-templates-pvc
